### ISSUE TITLE
Player

### ISSUE THREAD

**Issue by muezis** [maximelouet/spotly#11]
Hey, It's really good. This is probably the only app that allows me to select, copy, and perform other actions with text. And it has a great design. But there is one problem. Player. Please add a player. I learn the language by reading the lyrics, and it is important for me to be able to rewind and pause to listen a particular phrase again.

So far, your app isn't much better than just opening text on genius. But if you make a normal player that can be conveniently controlled, it will be the best that is available at the moment.

**Comment by maximelouet** [comment]
Hi, thank you for your interest in my project.

The goal of this app is to display the lyrics from the current playing song on Spotify. I do think it's better than "just opening text on genius" as it saves you the search (and can fetch other sites if your lyrics aren't on Genius).

Currently, I do not plan to include a custom Spotify player in the app as it's quite a lot of work and not the initial goal of the project. Controlling the music is up to the user and you may use whatever is at your disposal to do it easily.

I'm keeping this idea, maybe one day I'll include more content such as player, video links, etc :wink:
