### ISSUE TITLE
No lyrics

### ISSUE THREAD

**Issue by Letoux** [maximelouet/spotly#17]
No lyrics (or after a looooong time, i did not have some after 30 seconds) for the music "Aviron bayonnais (version en basque)" de "Chœur de l'Aviron".

**Comment by maximelouet** [comment]
Hi,

Genius does not have any lyrics for this song, and Musixmatch [has "unverified" lyrics](https://www.musixmatch.com/lyrics/Ch%C5%93urs-de-l-aviron/Aviron-Bayonnais).

As stated in the project README, the current strategy is to drop "unverified" lyrics as they are sometimes completely irrelevant.

So: this is completely expected on Spotly's side. To fix this, add the lyrics to Genius or review them on Musixmatch :slightly_smiling_face:
